package src.main.java;
// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: jflex/Trabalho.jflex


 /*  Esta seção é copiada antes da declaração da classe do analisador léxico.
  *  É nesta seção que se deve incluir imports e declaração de pacotes.
  *  Neste exemplo não temos nada a incluir nesta seção.
  */
  

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class LextTest {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\5\u0100\1\u0200\1\u0300\1\u0100\5\u0400\1\u0500\1\u0600"+
    "\1\u0700\6\u0100\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00"+
    "\3\u0100\1\u0e00\205\u0100\1\u0600\1\u0100\1\u0f00\1\u1000\1\u1100"+
    "\1\u1200\54\u0100\10\u1300\37\u0100\1\u0900\4\u0100\1\u1400\10\u0100"+
    "\1\u1500\2\u0100\1\u1600\1\u1700\1\u1200\1\u0100\1\u0500\1\u0100"+
    "\1\u1800\1\u1500\1\u0800\3\u0100\1\u1100\1\u1900\114\u0100\1\u1a00"+
    "\1\u1100\153\u0100\1\u1b00\11\u0100\1\u1c00\1\u1200\6\u0100\1\u1100"+
    "\u0f16\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\3\0\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\23\1\24"+
    "\1\25\1\26\1\27\2\0\1\30\1\31\1\32\2\30"+
    "\1\33\2\30\1\34\21\30\1\35\1\36\1\37\1\0"+
    "\1\40\1\0\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\43\1\47\1\50\2\43\1\51\1\43\1\52\1\53"+
    "\1\54\1\43\1\55\1\56\1\57\1\60\1\43\1\61"+
    "\3\43\1\62\1\63\1\64\7\0\1\3\u01da\0\12\65"+
    "\206\0\12\65\306\0\12\65\234\0\12\65\166\0\12\65"+
    "\140\0\12\65\166\0\12\65\106\0\12\65\u0116\0\12\65"+
    "\106\0\12\65\u0146\0\12\65\46\0\12\65\u012c\0\12\65"+
    "\200\0\12\65\246\0\12\65\6\0\12\65\266\0\12\65"+
    "\126\0\12\65\206\0\12\65\6\0\12\65\316\0\2\3"+
    "\u01a6\0\12\65\46\0\12\65\306\0\12\65\26\0\12\65"+
    "\126\0\12\65\u0196\0\12\65\6\0\u0100\3\240\0\12\65"+
    "\206\0\12\65\u012c\0\12\65\200\0\12\65\74\0\12\65"+
    "\220\0\12\65\166\0\12\65\146\0\12\65\206\0\12\65"+
    "\106\0\12\65\266\0\12\65\u0164\0\62\65\100\0\12\65"+
    "\266\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[7424];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\3\1\4\1\5\2\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\5\24\1\25\1\26"+
    "\7\27\1\30\1\2\1\31\1\1\1\2\1\32\1\33"+
    "\1\0\1\34\3\0\1\34\1\35\1\0\1\36\1\37"+
    "\1\40\1\41\4\24\2\27\1\42\5\27\1\43\1\44"+
    "\2\45\2\0\2\1\3\24\1\46\3\27\1\47\4\27"+
    "\2\0\1\50\1\51\1\24\1\52\1\53\1\27\1\54"+
    "\1\27\1\55\1\27\1\0\1\56\1\27\1\57\1\27"+
    "\1\60\1\27\1\61\1\62";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\66\0\154\0\154\0\242\0\330\0\154\0\u010e"+
    "\0\u0144\0\154\0\154\0\154\0\154\0\154\0\154\0\u017a"+
    "\0\u01b0\0\u01e6\0\u021c\0\154\0\u0252\0\u0288\0\u02be\0\u02f4"+
    "\0\u032a\0\u0360\0\u0396\0\u03cc\0\154\0\154\0\u0402\0\u0438"+
    "\0\u046e\0\u04a4\0\u04da\0\u0510\0\u0546\0\154\0\u057c\0\154"+
    "\0\u05b2\0\u05e8\0\154\0\154\0\u061e\0\u0654\0\u068a\0\u06c0"+
    "\0\u06f6\0\u017a\0\154\0\u072c\0\154\0\154\0\154\0\154"+
    "\0\u0762\0\u0798\0\u07ce\0\u0804\0\u083a\0\u0870\0\u0402\0\u08a6"+
    "\0\u08dc\0\u0912\0\u0948\0\u097e\0\154\0\154\0\154\0\u061e"+
    "\0\u09b4\0\u09ea\0\154\0\u0a20\0\u0a56\0\u0a8c\0\u0ac2\0\u02f4"+
    "\0\u0af8\0\u0b2e\0\u0b64\0\u0402\0\u0b9a\0\u0bd0\0\u0c06\0\u0c3c"+
    "\0\u0c72\0\u0ca8\0\u02f4\0\u02f4\0\u0cde\0\u0402\0\u0402\0\u0d14"+
    "\0\u0402\0\u0d4a\0\u0402\0\u0d80\0\u0db6\0\u02f4\0\u0dec\0\u0402"+
    "\0\u0e22\0\154\0\u0e58\0\u0402\0\u0402";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\3\1\36\1\3"+
    "\3\37\1\40\1\41\2\37\1\42\1\37\1\43\1\37"+
    "\1\44\1\45\4\37\1\46\1\47\1\50\1\22\14\51"+
    "\1\52\4\51\1\3\44\51\70\0\1\4\111\0\1\53"+
    "\47\0\1\54\55\0\2\55\4\0\14\55\1\56\13\55"+
    "\1\57\7\55\1\60\10\55\1\61\5\55\1\56\22\0"+
    "\1\62\42\0\1\62\14\0\1\63\4\0\1\64\55\0"+
    "\1\62\6\0\1\62\1\0\1\22\42\0\1\22\23\0"+
    "\1\65\70\0\1\66\65\0\1\67\65\0\1\70\61\0"+
    "\1\30\5\0\5\30\3\0\22\30\26\0\1\30\5\0"+
    "\5\30\3\0\13\30\1\71\6\30\26\0\1\30\5\0"+
    "\5\30\3\0\7\30\1\72\12\30\26\0\1\30\5\0"+
    "\5\30\3\0\11\30\1\73\10\30\26\0\1\30\5\0"+
    "\5\30\3\0\12\30\1\74\7\30\26\0\1\37\5\0"+
    "\5\37\3\0\22\37\26\0\1\37\5\0\5\37\3\0"+
    "\1\37\1\75\20\37\26\0\1\37\5\0\5\37\3\0"+
    "\11\37\1\76\10\37\26\0\1\37\5\0\5\37\3\0"+
    "\6\37\1\77\10\37\1\100\2\37\26\0\1\37\5\0"+
    "\5\37\3\0\5\37\1\101\12\37\1\102\1\37\26\0"+
    "\1\37\5\0\5\37\3\0\15\37\1\103\4\37\26\0"+
    "\1\37\5\0\5\37\3\0\5\37\1\104\14\37\67\0"+
    "\1\105\2\0\14\51\1\0\4\51\1\0\44\51\21\0"+
    "\1\106\55\0\1\107\65\0\1\107\10\0\1\62\42\0"+
    "\1\62\11\0\1\110\24\0\1\55\3\0\1\55\7\0"+
    "\1\55\2\0\1\55\1\0\1\55\17\0\1\107\27\0"+
    "\1\111\35\0\1\107\43\0\1\112\10\0\2\64\1\113"+
    "\2\0\1\114\60\64\22\0\1\30\5\0\5\30\3\0"+
    "\13\30\1\115\6\30\26\0\1\30\5\0\5\30\3\0"+
    "\1\30\1\116\20\30\26\0\1\30\5\0\5\30\3\0"+
    "\13\30\1\117\6\30\26\0\1\30\5\0\5\30\3\0"+
    "\17\30\1\120\2\30\26\0\1\37\5\0\5\37\3\0"+
    "\17\37\1\121\2\37\26\0\1\37\5\0\5\37\3\0"+
    "\16\37\1\122\3\37\26\0\1\37\5\0\5\37\3\0"+
    "\5\37\1\123\14\37\26\0\1\37\5\0\5\37\3\0"+
    "\21\37\1\124\26\0\1\37\5\0\5\37\3\0\11\37"+
    "\1\125\10\37\26\0\1\37\5\0\5\37\3\0\10\37"+
    "\1\126\11\37\26\0\1\37\5\0\5\37\3\0\1\37"+
    "\1\127\15\37\1\130\2\37\55\0\1\131\74\0\1\132"+
    "\7\0\1\113\105\0\1\30\5\0\5\30\3\0\11\30"+
    "\1\133\10\30\26\0\1\30\5\0\5\30\3\0\15\30"+
    "\1\134\4\30\26\0\1\30\5\0\5\30\3\0\1\30"+
    "\1\135\20\30\26\0\1\37\5\0\5\37\3\0\1\37"+
    "\1\136\20\37\26\0\1\37\5\0\5\37\3\0\5\37"+
    "\1\137\14\37\26\0\1\37\5\0\5\37\3\0\15\37"+
    "\1\140\4\37\26\0\1\37\5\0\5\37\3\0\11\37"+
    "\1\141\10\37\26\0\1\37\5\0\5\37\3\0\12\37"+
    "\1\142\7\37\26\0\1\37\5\0\5\37\3\0\4\37"+
    "\1\143\15\37\26\0\1\37\5\0\5\37\3\0\20\37"+
    "\1\144\1\37\62\0\1\132\54\0\1\145\42\0\1\30"+
    "\5\0\5\30\3\0\17\30\1\146\2\30\26\0\1\37"+
    "\5\0\5\37\3\0\1\37\1\147\20\37\26\0\1\37"+
    "\5\0\5\37\3\0\17\37\1\150\2\37\26\0\1\37"+
    "\5\0\5\37\3\0\15\37\1\151\4\37\15\0\1\152"+
    "\76\0\1\37\5\0\5\37\3\0\17\37\1\153\2\37"+
    "\26\0\1\37\5\0\5\37\3\0\12\37\1\154\7\37"+
    "\26\0\1\37\5\0\5\37\3\0\5\37\1\155\14\37"+
    "\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3726];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\2\11\2\1\1\11\2\1\6\11\4\1"+
    "\1\11\10\1\2\11\7\1\1\11\1\1\1\11\2\1"+
    "\2\11\1\0\1\1\3\0\1\1\1\11\1\0\4\11"+
    "\14\1\3\11\1\1\2\0\1\11\15\1\2\0\12\1"+
    "\1\0\4\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    
    /* Código arbitrário pode ser inserido diretamente no analisador dessa forma. 
     * Aqui podemos declarar variáveis e métodos adicionais que julgarmos necessários. 
     */
    private int ntk;
    
    public int readedTokens(){
       return ntk;
    }
    private Token symbol(TOKEN_TYPE t) {
        ntk++;
        return new Token(t,yytext(), yyline+1, yycolumn+1);
        
    }
    private Token symbol(TOKEN_TYPE t, Object value) {
        ntk++;
        return new Token(t, value, yyline+1, yycolumn+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LextTest(java.io.Reader in) {
      ntk = 0; // Isto é copiado direto no construtor do lexer. 
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 51: break;
          case 2:
            { throw new RuntimeException("Illegal character <"+yytext()+">");
            }
            // fall through
          case 52: break;
          case 3:
            { /* Não faz nada  */
            }
            // fall through
          case 53: break;
          case 4:
            { return symbol(TOKEN_TYPE.NEGATION);
            }
            // fall through
          case 54: break;
          case 5:
            { return symbol(TOKEN_TYPE.MODULUS);
            }
            // fall through
          case 55: break;
          case 6:
            { return symbol(TOKEN_TYPE.OPEN_PARENTHESIS);
            }
            // fall through
          case 56: break;
          case 7:
            { return symbol(TOKEN_TYPE.CLOSE_PARENTHESIS);
            }
            // fall through
          case 57: break;
          case 8:
            { return symbol(TOKEN_TYPE.MULTIPLICATION);
            }
            // fall through
          case 58: break;
          case 9:
            { return symbol(TOKEN_TYPE.ADDITION);
            }
            // fall through
          case 59: break;
          case 10:
            { return symbol(TOKEN_TYPE.COMMA);
            }
            // fall through
          case 60: break;
          case 11:
            { return symbol(TOKEN_TYPE.SUBTRACTION);
            }
            // fall through
          case 61: break;
          case 12:
            { return symbol(TOKEN_TYPE.DOT);
            }
            // fall through
          case 62: break;
          case 13:
            { return symbol(TOKEN_TYPE.DIVISION);
            }
            // fall through
          case 63: break;
          case 14:
            { return symbol(TOKEN_TYPE.INT_LITERAL, Integer.parseInt(yytext()));
            }
            // fall through
          case 64: break;
          case 15:
            { return symbol(TOKEN_TYPE.COLON);
            }
            // fall through
          case 65: break;
          case 16:
            { return symbol(TOKEN_TYPE.SEMICOLON);
            }
            // fall through
          case 66: break;
          case 17:
            { return symbol(TOKEN_TYPE.LESS_THAN);
            }
            // fall through
          case 67: break;
          case 18:
            { return symbol(TOKEN_TYPE.ASSIGNMENT);
            }
            // fall through
          case 68: break;
          case 19:
            { return symbol(TOKEN_TYPE.GREATER_THAN);
            }
            // fall through
          case 69: break;
          case 20:
            { return symbol(TOKEN_TYPE.TYPE);
            }
            // fall through
          case 70: break;
          case 21:
            { return symbol(TOKEN_TYPE.OPEN_BRACKET);
            }
            // fall through
          case 71: break;
          case 22:
            { return symbol(TOKEN_TYPE.CLOSE_BRACKET);
            }
            // fall through
          case 72: break;
          case 23:
            { return symbol(TOKEN_TYPE.IDENTIFIER);
            }
            // fall through
          case 73: break;
          case 24:
            { return symbol(TOKEN_TYPE.OPEN_BRACE);
            }
            // fall through
          case 74: break;
          case 25:
            { return symbol(TOKEN_TYPE.CLOSE_BRACE);
            }
            // fall through
          case 75: break;
          case 26:
            { return symbol(TOKEN_TYPE.INEQUALITY);
            }
            // fall through
          case 76: break;
          case 27:
            { return symbol(TOKEN_TYPE.AND);
            }
            // fall through
          case 77: break;
          case 28:
            { return symbol(TOKEN_TYPE.FLOAT_LITERAL, Float.parseFloat(yytext()));
            }
            // fall through
          case 78: break;
          case 29:
            { yybegin(COMMENT);
            }
            // fall through
          case 79: break;
          case 30:
            { return symbol(TOKEN_TYPE.TYPE_ASSIGMENT);
            }
            // fall through
          case 80: break;
          case 31:
            { return symbol(TOKEN_TYPE.LESS_THAN_OR_EQUAL);
            }
            // fall through
          case 81: break;
          case 32:
            { return symbol(TOKEN_TYPE.EQUALITY);
            }
            // fall through
          case 82: break;
          case 33:
            { return symbol(TOKEN_TYPE.GREATER_THAN_OR_EQUAL);
            }
            // fall through
          case 83: break;
          case 34:
            { return symbol(TOKEN_TYPE.IF_KEYWORD);
            }
            // fall through
          case 84: break;
          case 35:
            { return symbol(TOKEN_TYPE.OR);
            }
            // fall through
          case 85: break;
          case 36:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 86: break;
          case 37:
            { return symbol(TOKEN_TYPE.CHAR_LITERAL, yytext().replace("\'", ""));
            }
            // fall through
          case 87: break;
          case 38:
            { return symbol(TOKEN_TYPE.INT_KEYWORD);
            }
            // fall through
          case 88: break;
          case 39:
            { return symbol(TOKEN_TYPE.NEW_KEYWORD);
            }
            // fall through
          case 89: break;
          case 40:
            { return symbol(TOKEN_TYPE.BOOL_KEYWORD);
            }
            // fall through
          case 90: break;
          case 41:
            { return symbol(TOKEN_TYPE.CHAR_KEYWORD);
            }
            // fall through
          case 91: break;
          case 42:
            { return symbol(TOKEN_TYPE.DATA_KEYWORD);
            }
            // fall through
          case 92: break;
          case 43:
            { return symbol(TOKEN_TYPE.ELSE_KEYWORD);
            }
            // fall through
          case 93: break;
          case 44:
            { return symbol(TOKEN_TYPE.NULL_LITERAL);
            }
            // fall through
          case 94: break;
          case 45:
            { return symbol(TOKEN_TYPE.READ_KEYWORD);
            }
            // fall through
          case 95: break;
          case 46:
            { return symbol(TOKEN_TYPE.FLOAT_KEYWORD);
            }
            // fall through
          case 96: break;
          case 47:
            { return symbol(TOKEN_TYPE.PRINT_KEYWORD);
            }
            // fall through
          case 97: break;
          case 48:
            { return symbol(TOKEN_TYPE.BOOL_LITERAL, Boolean.parseBoolean(yytext()));
            }
            // fall through
          case 98: break;
          case 49:
            { return symbol(TOKEN_TYPE.RETURN_KEYWORD);
            }
            // fall through
          case 99: break;
          case 50:
            { return symbol(TOKEN_TYPE.ITERATE_KEYWORD);
            }
            // fall through
          case 100: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
